name: Build and Push Python Image to Google Cloud Platform
on:
    push:
        branches: [main]
jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: cloudrun-flask
            PROJECT_ID: flask-github-action

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # setup-gcloud@v1 ，是指使用setup-gcloud動作的版本號
            - uses: google-github-actions/setup-gcloud@v1
              with:
                  service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                  project_id: ${{ env.PROJECT_ID }}
                  install_components: docker
                  export_default_credentials: true

            - name: Build Docker Image
              run: |
                  docker build -t $IMAGE_NAME:latest .

            - name: Automatic Tagging of Releases
              id: increment-git-tag
              run: |
                  bash ./scripts/git_update.sh -v major


            - name: Configure Docker Client
              run: |-
                  gcloud auth configure-docker --quiet
                  gcloud auth configure-docker asia-east1-docker.pkg.dev --quiet
                  gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-east1-docker.pkg.dev

            # push image to Container Resgistry , but it end sevice on May 2024.
            # - name: Push Docker Image to Container Registry (GCR)
            #   env:
            #       GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
            #   run: |-
            #       docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            #       docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
            #       docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            #       docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

            - name: Push Docker Image to Artifact Registry
              env:
                  GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
              run: |-
                  DOCKER_REPO=asia-east1-docker.pkg.dev/$PROJECT_ID/docker-images
                  DOCKER_REPO_LOWER=$(echo "$DOCKER_REPO" | tr '[:upper:]' '[:lower:]')
                  docker tag $IMAGE_NAME:latest $DOCKER_REPO:latest
                  docker tag $IMAGE_NAME:latest $DOCKER_REPO:$GIT_TAG
                  docker push $DOCKER_REPO:latest
                  docker push $DOCKER_REPO:$GIT_TAG
